from django.urls import path
from buyers.views import *

urlpatterns = [
    path("", by_index, name="by_index"),
    path("home/", by_home, name="by_home"),
    path("login/", by_login, name="by_login"),
    path("register/", by_register, name="by_register"),
    path("profile/", by_profile, name="by_profile"),
    path("profile/update/", by_update_profile, name="by_update_profile"),
    path("blog/", by_blog, name="by_blog"),
    path("cart/", by_cart, name="by_cart"),
    path("cart/add/<int:variant_id>/", add_to_cart, name="by_add_to_cart"),
    path("wishlist/add/<int:variant_id>/", add_to_wishlist, name="by_add_wishlist"),
    path("wishlist/", by_wishlist, name="by_wishlist"),
    path("wishlist/remove/<int:item_id>/", remove_wishlist_item, name="by_wishlist_remove"),
    path("checkout/", by_checkout, name="by_checkout"),
    path("product/<int:variant_id>/", by_product, name="by_product"),
    path("contact/", by_contact, name="by_contact"),
    path("shop/", by_shop, name="by_shop"),
    path("shop/api/", by_shop_api, name="by_shop_api"),
    path("wishlist/toggle/<int:variant_id>/", toggle_wishlist_api, name="by_toggle_wishlist_api"),
    path("thankyou/", by_thankyou, name="by_thankyou"),
    path("logout/", by_logout, name="by_logout"),
    path("cart/remove/<int:item_id>/", remove_from_cart, name="by_remove_from_cart"),
    path("checkout/place-order/", place_order, name="by_place_order"),
    path("checkout/verify-payment/", verify_payment, name="by_verify_payment"),
    path("checkout/cancel-order/", cancel_unpaid_order, name="by_cancel_unpaid_order"),
    path("history/", by_history, name="by_history"),
    path("order/<int:order_id>/return/", by_return_order, name="by_return_order"),
    path("order/<int:order_id>/cancel/", by_cancel_order, name="by_cancel_order"),
    path("order/<int:order_id>/items/", by_order_items_api, name="by_order_items_api"),
    path("order/<int:order_id>/receipt/", by_order_receipt, name="by_order_receipt"),
]
