# Generated by Django 5.2.11 on 2026-04-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='name',
        ),
    ]
