# Generated by Django 5.2.11 on 2026-03-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_productvariant_main_image_productvariantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantimage',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='main_image',
        ),
        migrations.DeleteModel(
            name='ProductColorImage',
        ),
        migrations.DeleteModel(
            name='ProductVariantImage',
        ),
    ]
