# Generated by Django 5.2.10 on 2026-04-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_workers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
