# Generated by Django 5.2.10 on 2026-04-03 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_blogs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='last_working_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_leaves', models.FloatField(default=0)),
                ('unpaid_leaves', models.FloatField(default=0)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='admin_panel.workers')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('worker', 'month', 'year')},
            },
        ),
    ]
