# Generated by Django 5.2.10 on 2026-04-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_workers_joining_date_workers_last_working_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryhistory',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='approved_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='unpaid_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_histories', to='admin_panel.workers'),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
