# Generated by Django 5.2.11 on 2026-04-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_salaryhistory_paid_at_salaryhistory_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='last_working_date',
        ),
        migrations.DeleteModel(
            name='SalaryHistory',
        ),
    ]
