# Generated by Django 4.1 on 2026-02-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='category',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Emergency', 'Emergency'), ('Casual', 'Casual')], default='Casual', max_length=20),
        ),
        migrations.AddField(
            model_name='leave',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
