# Generated by Django 5.2.11 on 2026-04-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_workers_joining_date_workers_last_working_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='last_working_date',
        ),
        migrations.DeleteModel(
            name='SalaryHistory',
        ),
    ]
