# Generated by Django 5.2.11 on 2026-04-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_remove_workers_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workers',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
