# Generated by Django 5.2.10 on 2026-04-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
