# Generated by Django 5.2.10 on 2026-04-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_product_scent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='scent_name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='scent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
