# Generated by Django 5.2.10 on 2026-04-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_remove_product_scent_name_productvariant_scent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
