# Generated by Django 5.2.10 on 2026-04-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantspec',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
