# Generated by Django 4.1 on 2026-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_buyer_address_buyer_city_buyer_pincode_buyer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='buyers/'),
        ),
    ]
