# Generated by Django 4.1 on 2026-02-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI / GPay / PhonePe / Paytm'), ('cash_on_delivery', 'Cash on Delivery')], max_length=50),
        ),
    ]
