# Generated by Django 4.1 on 2026-02-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0008_add_return_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_requested_at',
        ),
    ]
